### ISSUE TITLE
Question about schematic.

### ISSUE THREAD

**Issue by mainiak** [Arachnid/dfpga#1]
Hi.

Sorry for dummy question, but what is circuit IC6P in schematics good for?
That's the little board beside (bigger) slice board in your photo?
And what are values for C1-C6?

What is Q1-Q8? And what are R1-R8 values?

I tried to find answer inside schematic or in article but without luck.
http://blog.notdot.net/2012/10/Build-your-own-FPGA

What am I overlooking?

Thank you in advance.

**Comment by penserbjorne** [comment]
Hi @mainiak .

Q1-Q8 I think are transistors, just for the led's.
R1-R8 depend from the led's value.
C1-C6 are just capacitor to reduce the noise (I guess), you can use (maybe) with 0.1 microF.

Regards!!! :D

**Comment by Arachnid** [comment]
I actually don't have Eagle installed anymore - I moved to DipTrace - so I'm going to have to go off memory here.

IC6P is, I think, the power pins for IC6. Although they're all shown as separate components, they're actually parts of the same IC.

@penserbjorne is right about the components; R1-R8 should be selected such that they limit the LED current to ~5mA, and C1-C6 can be 0.1uF ceramics.

**Comment by mainiak** [comment]
Thank you @penserbjorne and @Arachnid for answering my 3 years old question. You made my day :)
