### ISSUE TITLE
What does arduino? :(

### ISSUE THREAD

**Issue by penserbjorne** [Arachnid/dfpga#2]
Hi Nick.

First of all, thanks for this great project :)

I have a doubt, on the [video](https://www.youtube.com/watch?v=7r0CuxFMGBQ) I see you use an Arduino to load the program, how do you do it? Can you share the program/diagram (If you still have it)? Or at least explain it? :)

And I don't have very clear how to use the switches :/ so, if you can say something about it would be great!

Thanks!

**Comment by Arachnid** [comment]
I don't still have the program, but it's pretty simple - just stick the data you want to shift into the modules in a variable and use `shiftOut` to send it.

What switches are you referring to?

**Comment by penserbjorne** [comment]
Ok, let me read about shiftOut :)

I mean the external switches conected, I dont know if are just to program (send data to registers) or as inputs or both.

And the jumpers, the same as the switches, are just to select if the lines are input/output and/or for expasion?

**Comment by Arachnid** [comment]
It's been a long time, but IIRC, the switches and jumpers let you select the input and output routing for the programming data signals, so that you can chain them in the right directions and program them all at once.

**Comment by penserbjorne** [comment]
Ok, I'll be working on that.

Thanks!
